version: '3'

tasks:
  build:
    dir: mp4tostream
    cmds:
      - go build -o bin/bootstrap main.go
  
  test:
    dir: mp4tostream
    cmds:
      - go test ./...
  
  tidy:
    dir: mp4tostream
    cmds:
      - go mod tidy
  
  sam-build:
    cmds:
      - sam build

  # Build before deploying
  deploy:
    deps: [sam-build]
    cmds:
      - sam deploy
  
  destroy:
    cmds:
      - sam delete
  
  build-layer-bin-ffmpeg:
    dir: build/layer
    cmds:
      - curl -sL https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-arm64-static.tar.xz | tar xJ --strip-components=1 -C .
      - mv ffmpeg bin/ffmpeg
      - mv ffprobe bin/ffprobe
      - chmod +x bin/ffmpeg
      - chmod +x bin/ffprobe