version: '3'

tasks:
  # build-mp4:
  #   dir: mp4tostream
  #   cmds:
  #     - go build -o bootstrap main.go
  
  test:
    dir: mp4tostream
    cmds:
      - go test ./...
  
  tidy:
    dir: mp4tostream
    cmds:
      - go mod tidy
  
  # build-m3u8:
  #   dir: m3u8tostream
  #   cmds:
  #     - go build -o bootstrap main.go

  sam-build:
    deps: [build-layer-bin-ffmpeg]
    cmds:
      - sam build

  # Build before deploying
  deploy:
    deps: [sam-build]
    cmds:
      - sam deploy
  
  destroy:
    cmds:
      - sam delete
  
  build-layer-bin-ffmpeg:
    dir: build/layer
    cmds:
      - mkdir -p bin
      - curl -L https://www.johnvansickle.com/ffmpeg/old-releases/ffmpeg-4.4.1-arm64-static.tar.xz -o ffmpeg-release-i686-static.tar.xz
      - tar -xJf ffmpeg-release-i686-static.tar.xz --strip-components=1 -C bin
      - mv bin/ffmpeg* bin/ffmpeg
      - mv bin/ffprobe* bin/ffprobe
      - rm ffmpeg-release-i686-static.tar.xz
      - chmod +x bin/ffmpeg bin/ffprobe
      - zip -r9 ../layer.zip .
    sources:
      - bin/ffmpeg
      - bin/ffprobe
    generates:
      - ../layer.zip
      